version: "3.4"
services:
  bee:
    image: "bee.swarm.public.dappnode.eth:1.0.0"
    build:
      context: bee
      args:
        UPSTREAM_VERSION: v1.8.0-rc3
    ports:
      - "1634:1634"
    volumes:
      - "bee-data:/home/bee/.bee"
    environment:
      BEE_PASSWORD: ""
      BEE_SWAP_ENDPOINT: "https://rpc.gnosischain.com"
      BEE_FULL_NODE: "true"
      BEE_MAINNET: "true"
      BEE_DEBUG_API_ENABLE: "true"
      BEE_CORS_ALLOWED_ORIGINS: "*"
      EXTRA_OPTS: ""
    restart: unless-stopped
  dashboard:
    image: "dashboard.swarm.public.dappnode.eth:1.0.0"
    build:
      context: dashboard
    restart: unless-stopped
volumes:
  bee-data: {}
