version: "3.4"
services:
  bee:
    image: "bee.swarm-testnet.public.dappnode.eth:1.0.0"
    build:
      context: bee
      args:
        UPSTREAM_VERSION: v1.8.1
    ports:
      - "1734:1734"
    volumes:
      - "bee-data:/home/bee/.bee"
    environment:
      BEE_SWAP_ENDPOINT: "http://goerli-geth.dappnode:8545"
      BEE_RESOLVER_OPTIONS: "http://goerli-geth.dappnode:8545"
      BEE_FULL_NODE: "true"
      BEE_DEBUG_API_ENABLE: "true"
      BEE_CORS_ALLOWED_ORIGINS: "*"
      BEE_API_ADDR: ":1733"
      BEE_P2P_ADDR: ":1734"
      BEE_DEBUG_API_ADDR: ":1735"
      BEE_WELCOME_MESSAGE: "Swarming on DAppNode \U0001F41D"
      BEE_PASSWORD_FILE: /home/bee/.bee/password
      BEE_BOOTNODE: /dnsaddr/testnet.ethswarm.org
      BEE_MAINNET: "false"
      EXTRA_OPTS: ""
    restart: unless-stopped
  dashboard:
    image: "dashboard.swarm-testnet.public.dappnode.eth:1.0.0"
    build:
      context: dashboard
    restart: unless-stopped
volumes:
  bee-data: {}
