name: "Main"
on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: 'Type of version increment: patch, minor, or major'
        required: true
        default: patch
        options:
        - patch
        - minor
        - major

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npx @dappnode/dappnodesdk@0.3.22 build --skip_save

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Publish
        run: npx @dappnode/dappnodesdk@0.3.22 publish patch --github-release --eth_provider=${{ secrets.ETH_PROVIDER }} --content_provider=pinata
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
          DEVELOPER_ADDRESS: "0xdAD64d07A318476dc48257a0bB53a8e9a26C6B33"
